Traceback (most recent call last):
  File "C:\Users\U727148\AppData\Local\anaconda3\envs\pymc_env\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\U727148\AppData\Local\anaconda3\envs\pymc_env\Lib\site-packages\nbclient\client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\U727148\AppData\Roaming\Python\Python312\site-packages\jupyter_core\utils\__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\U727148\AppData\Local\anaconda3\envs\pymc_env\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\U727148\AppData\Local\anaconda3\envs\pymc_env\Lib\site-packages\nbclient\client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "C:\Users\U727148\AppData\Local\anaconda3\envs\pymc_env\Lib\site-packages\nbclient\client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\U727148\AppData\Local\anaconda3\envs\pymc_env\Lib\site-packages\nbclient\client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import matplotlib.pyplot as plt
import pandas as pd

# Assuming df_lca_outcomes is your DataFrame
data = df_lca_outcomes['solution (no. of groups and distribution)'].value_counts()

# Define pastel colors
colors = ['#FFC1C1', '#FF6961', '#FFB2A7', '#FFDAC1', '#FF928B']

# Create the pie chart
plt.figure(figsize=(8, 8))
plt.pie(data, labels=data.index, autopct='%1.1f%%', startangle=140, colors=colors, textprops={'fontsize': 20})


# Add a title
plt.title('Distribution of Number of Classes')

# Show the plot
plt.show()

------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
Cell [1;32mIn[43], line 5[0m
[0;32m      2[0m [38;5;28;01mimport[39;00m [38;5;21;01mpandas[39;00m [38;5;28;01mas[39;00m [38;5;21;01mpd[39;00m
[0;32m      4[0m [38;5;66;03m# Assuming df_lca_outcomes is your DataFrame[39;00m
[1;32m----> 5[0m data [38;5;241m=[39m [43mdf_lca_outcomes[49m[[38;5;124m'[39m[38;5;124msolution (no. of groups and distribution)[39m[38;5;124m'[39m][38;5;241m.[39mvalue_counts()
[0;32m      7[0m [38;5;66;03m# Define pastel colors[39;00m
[0;32m      8[0m colors [38;5;241m=[39m [[38;5;124m'[39m[38;5;124m#FFC1C1[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124m#FF6961[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124m#FFB2A7[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124m#FFDAC1[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124m#FF928B[39m[38;5;124m'[39m]

[1;31mNameError[0m: name 'df_lca_outcomes' is not defined

